qa: 
 prefix: "https://lootcrate-qa.herokuapp.com"
 admin: "https://loot-admin-qa.herokuapp.com/admin/login"
 app: "lootcrate-qa"
qa2:
 prefix: "https://lootcrate-qa2.herokuapp.com"
 admin: "https://lootcrate-qa2-admin.herokuapp.com/admin/login"
 app: "lootcrate-qa2"
staging:
 prefix: "https://lootcrate-staging.herokuapp.com"
 admin: "https://lootcrate-staging-admin.herokuapp.com/admin/login"
 app: "lootcrate-staging"
goliath:
 prefix: "https://lootcrate-goliath.herokuapp.com"
 admin: "https://lootcrate-goliath-admin.herokuapp.com/admin/login"
 app: "lootcrate-goliath"
loadtest:
 prefix: "https://lootcrate-load-test.herokuapp.com"
 admin: "https://loot-admin-qa.herokuapp.com/admin/login"
 app: "lootcrate-load-test"
local:
 prefix: "localhost:3000"
home:
 url: "/?username=lootcrateis25timesgreaterthanthecompetition"
signup:
 url: "/users/sign_up"
checkout:
 url: "/1-month-subscription/checkouts/new"
generic:
 url: "/?username=lootcrateis25timesgreaterthanthecompetition"
subscribe:
 url: "/join"
my_account:
 url: "/user_accounts"
mailinator:
 url: "https://mailinator.com"
recurly:
 url: "https://recurly.com"
level_up:
 url: "/level_up"
fallout4:
 url: "/fallout4"
