qa: 
 prefix: "https://lootcrate-qa.herokuapp.com"
qa2:
 prefix: "https://lootcrate-qa2.herokuapp.com"
staging:
 prefix: "https://lootcrate-staging.herokuapp.com"
goliath:
 prefix: "https://lootcrate-goliath.herokuapp.com"
local:
 prefix: "localhost:3000"
home:
 url: "/?username=lootcrateis25timesgreaterthanthecompetition"
signup:
 url: "/users/sign_up"
checkout:
 url: "/1-month-subscription/checkouts/new"
generic:
 url: "/?username=lootcrateis25timesgreaterthanthecompetition"
subscribe:
 url: "/join"
my_account:
 url: "/user_accounts"
mailinator:
 url: "https://mailinator.com"
admin:
 url: "https://loot-admin-qa.herokuapp.com/admin/login"
recurly:
 url: "https://recurly.com"
level_up:
 url: "/level_up"
