# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

# Defaults

MAILCHIMP_API_KEY: 5efbd6fac3e45048504d739a50fd587b-us9
MAILCHIMP_LIST_ID: 11b434baec
MANDRILL_API_KEY: 7NH_F06f5G_aRz2Dwgs4tg
FACEBOOK_KEY: "929669527050324"
FACEBOOK_SECRET: f005551d28238a9a00ee0e16bb671bc7
ZENDESK_API_URL: "https://lootcrate1421885692.zendesk.com/api/v2"
ZENDESK_API_USERNAME: "chris@lootcrate.com"
ZENDESK_API_TOKEN: "6NRHvlDRyzBFh29T2ACwFtbJxpSKGrwuCqvVBjtk"
GIZMO_USER: ricardo.rivas@crowdint.com
GIZMO_PASSWORD: pdmy7HG7YXMexz
GIZMO_URI: "https://restapi.surveygizmo.com/v4"
GIZMO_SURVEY_ID: "1971004"
FRIENDBUY_API_KEY: a41ad3d1-6a69-46d4-b012-be946f02cb5a
FRIENDBUY_API_SECRET: 4cf32209-d435-407b-864b-a9423ba741f2
FRIENDBUY_PURL_WIDGET_CAMPAIGN_ID: "13099"
FRIENDBUY_CONVERSION_CAMPAIGN: bmf-dzh
FRIENDBUY_SITE_ID: site-54108c4d-host
FRIENDBUY_MENU_CAMPAIGN: bmf-dzi
FRIENDBUY_EMAIL_CAMPAIGN_SPLASH_WIDGET: bmf-dAR
CHARGIFY_INTERNATIONAL_PRODUCT_FAMILY_ID: '442940'
CHARGIFY_CANADIAN_PRODUCT_FAMILY_ID: '442940'
CHARGIFY_DOMESTIC_PRODUCT_FAMILY_ID: '442941'
SAILTHRU_LOOTCRATE_DOMAIN: horizon.staging.lootcrate.com
SAILTHRU_API_KEY: 1c9ba94859c98db46ef2b7ce855d8d87
SAILTHRU_API_SECRET: aabf070535fe99723f26afdab31c3c61
SAILTHRU_API_URL: https://api.sailthru.com
S3_KEY: AKIAJCSPNMNXEXYHZCLA
S3_SECRET: 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
HIDE_COUPON_FIELD: false
RECURLY_SUBDOMAIN: lootcrate-sandbox
RECURLY_API_KEY: 86e6f5e2611442738963065eaa4dcb27
RECURLY_HTTP_AUTH_USERNAME: 'lootcrate'
RECURLY_HTTP_AUTH_PASSWORD: 'nopasswordhere'
RECURLY_PUBLIC_TOKEN: 'sjc-jP4zBgOHC0YhbBRt8R3y6y'
AVATAX_ACCOUNT_NUMBER: '1100147534'
AVATAX_LICENSE_KEY: 'AC5EA3208C5C90DC'
AVATAX_SERVICE_URL: 'https://development.avalara.net'
SMARTY_STREETS_AUTH_ID: '977792f9-f72c-4dc0-b7d5-7c2f1a223818'
SMARTY_STREETS_AUTH_TOKEN: 'S7oNo3vhRHUJ2iMoDThr'
BLOCK_ADMIN_USERS: false

production:
  MAILCHIMP_API_KEY: 3ee84b6d166c377e6757126b3641420f-us5
  MAILCHIMP_LIST_ID: b399d5f65c
  MANDRILL_API_KEY: 7NH_F06f5G_aRz2Dwgs4tg
  MANDRILL_USERNAME: chris@lootcrate.com
  ZENDESK_API_URL: "https://lootcrate.zendesk.com/api/v2"
  FRIENDBUY_API_KEY: 5308339d-6b2c-47fd-9f1d-7c9276808dd4
  FRIENDBUY_API_SECRET: baa43a4f-fcb1-4347-9008-618952ea1212
  FRIENDBUY_PURL_WIDGET_CAMPAIGN_ID: "12700"
  FRIENDBUY_CONVERSION_CAMPAIGN: Rh-b5j
  FRIENDBUY_SITE_ID: site-90b43ebb-www.lootcrate.com
  FRIENDBUY_MENU_CAMPAIGN: Rh-cta
  FRIENDBUY_EMAIL_CAMPAIGN_SPLASH_WIDGET: Rh-dAS
  CHARGIFY_INTERNATIONAL_PRODUCT_FAMILY_ID: '447626'
  CHARGIFY_CANADIAN_PRODUCT_FAMILY_ID: '447625'
  CHARGIFY_DOMESTIC_PRODUCT_FAMILY_ID: '447628'
  SAILTHRU_LOOTCRATE_DOMAIN: horizon.lootcrate.com
  SAILTHRU_API_KEY: fa9054964501548012cc5d8308ca496d
  SAILTHRU_API_SECRET: 6951bf61c4c299d639648148cbf0ba94
  SAILTHRU_API_URL: https://api.sailthru.com
  HIDE_COUPON_FIELD: false
