# TODO deploy 3 - change production subdomain back to real production after staging tests 
test:
  authorize_dot_net_subdomain: lootcratetest
  braintree_subdomain: lootcratetest-braintree
  api_key: DFLe4nAkwg13WPSwqmWP
  shared_key: ZgFQJ9JH2mU8izXUMYLJ
  shared_braintree_key: vUsFr4NBPQeeLIvCjcVj
development:
  authorize_dot_net_subdomain: lootcratetest
  braintree_subdomain: lootcratetest-braintree
  api_key: DFLe4nAkwg13WPSwqmWP
  shared_key: ZgFQJ9JH2mU8izXUMYLJ
  shared_braintree_key: vUsFr4NBPQeeLIvCjcVj
staging:
  authorize_dot_net_subdomain: lootcratetest
  braintree_subdomain: lootcratetest-braintree
  api_key: DFLe4nAkwg13WPSwqmWP
  shared_key: ZgFQJ9JH2mU8izXUMYLJ
  shared_braintree_key: vUsFr4NBPQeeLIvCjcVj
production:
  authorize_dot_net_subdomain: lootcrate
  braintree_subdomain: lootcrate2
  api_key: DFLe4nAkwg13WPSwqmWP
  shared_key: o5MDRwoYQhLwTn9JoUpS
  shared_braintree_key: w37fc3uH3Conl2jx7