au_one_month_sub: "au-1-month-subscription"
au_three_month_sub: "au-3-month-subscription"
au_six_month_sub:  "au-6-month-subscription"
au_twelve_month_sub:  "au-12-month-subscription"
ca_one_month_sub: "ca-1-month-subscription"
ca_three_month_sub: "ca-3-month-subscription"
ca_six_month_sub:  "ca-6-month-subscription"
ca_twelve_month_sub:  "ca-12-month-subscription"
de_one_month_sub: "de-1-month-subscription"
de_three_month_sub: "de-3-month-subscription"
de_six_month_sub:  "de-6-month-subscription"
de_twelve_month_sub:  "de-12-month-subscription"
dk_one_month_sub: "dk-1-month-subscription"
dk_three_month_sub: "dk-3-month-subscription"
dk_six_month_sub:  "dk-6-month-subscription"
dk_twelve_month_sub:  "dk-12-month-subscription"
fi_one_month_sub: "fi-1-month-subscription"
fi_three_month_sub: "fi-3-month-subscription"
fi_six_month_sub:  "fi-6-month-subscription"
fi_twelve_month_sub:  "fi-12-month-subscription"
fr_one_month_sub: "fr-1-month-subscription"
fr_three_month_sub: "fr-3-month-subscription"
fr_six_month_sub:  "fr-6-month-subscription"
fr_twelve_month_sub:  "fr-12-month-subscription"
gb_one_month_sub: "gb-1-month-subscription"
gb_three_month_sub: "gb-3-month-subscription"
gb_six_month_sub:  "gb-6-month-subscription"
gb_twelve_month_sub:  "gb-12-month-subscription"
ie_one_month_sub: "ie-1-month-subscription"
ie_three_month_sub: "ie-3-month-subscription"
ie_six_month_sub:  "ie-6-month-subscription"
ie_twelve_month_sub:  "ie-12-month-subscription"
nl_one_month_sub: "nl-1-month-subscription"
nl_three_month_sub: "nl-3-month-subscription"
nl_six_month_sub:  "nl-6-month-subscription"
nl_twelve_month_sub:  "nl-12-month-subscription"
no_one_month_sub: "no-1-month-subscription"
no_three_month_sub: "no-3-month-subscription"
no_six_month_sub:  "no-6-month-subscription"
no_twelve_month_sub:  "no-12-month-subscription"
nz_one_month_sub: "nz-1-month-subscription"
nz_three_month_sub: "nz-3-month-subscription"
nz_six_month_sub:  "nz-6-month-subscription"
nz_twelve_month_sub:  "nz-12-month-subscription"
se_one_month_sub: "se-1-month-subscription"
se_three_month_sub: "se-3-month-subscription"
se_six_month_sub:  "se-6-month-subscription"
se_twelve_month_sub:  "se-12-month-subscription"
one_month_sub: "1-month-subscription"
three_month_sub: "3-month-subscription"
six_month_sub: "6-month-subscription"
twelve_month_sub: "12-month-subscription"
shipping_cost: "6.00"
tax: "0.99"

amiibo_crate_three_weekly_payments: "amiibo-crate-three-weekly-payments"
amiibo_crate_single_payment: "amiibo-crate-single-payment"
