about_us:
 url: '/about_us'
home:
 url: "/?username=lootcrateis25timesgreaterthanthecompetition"
signup:
 url: "/users/sign_up"
checkout:
 url: "/1-month-subscription/checkouts/new"
core_opc:
  url: "/lp/lootcrate-1"
anime_opc:
  url: "/lp/lootanime-1"
gaming_opc:
  url: "/lp/lootgaming-1"
generic:
 url: "/?username=lootcrateis25timesgreaterthanthecompetition"
subscribe:
 url: "/join"
my_account:
 url: "/user_accounts"
mailinator:
 url: "https://mailinator.com"
recurly:
 url: "https://recurly.com"
fallout4:
 url: "/fallout4"
lootcrate_landing:
 url: "/subscription-crates/lootcrate"
lootcrate_subscribe:
 url: "/subscription-crates/lootcrate/plans"
lootcrate_checkout:
 url: "/1-month-subscription/checkouts/new"
levelup_subscribe:
 url: "/level_up"
anime_landing:
 url: "/subscription-crates/anime"
anime_subscribe:
 url: "/subscription-crates/anime/plans"
anime_checkout:
 url: "/anime-1-month-subscription/checkouts/new"
pets_landing:
 url: "/subscription-crates/pets"
pets_subscribe:
 url: "/subscription-crates/pets/plans"
pets_checkout:
 url: "/pets-1-month-subscription/checkouts/new"
firefly_landing:
 url: "/subscription-crates/firefly"
firefly_subscribe:
 url: "/subscription-crates/anime/plans"
firefly_checkout:
 url: "/firefly-2-month-subscription/checkouts/new"
gaming_landing:
 url: "/subscription-crates/gaming"
gaming_subscribe:
 url: "/subscription-crates/gaming/plans"
gaming_checkout:
 url: "/gaming-1-month-subscription/checkouts/new"
dx_landing:
 url: "/subscription-crates/lcdx"
dx_subscribe:
 url: "/subscription-crates/lcdx/plans"
dx_checkout:
 url: "/lcdx-1-month-subscription/checkouts/new"
pewdiepie:
 url: "/referrers/pewdiepie"
boogie2988:
 url: "/referrers/boogie2988"
tradechat:
 url: "/referrers/tradechat"
alchemy:
 url: "/alchemy/login"
pins:
 url: "/pins"
star_wars_landing:
 url: "/limited-edition-crates/star-wars-crate"
call_of_duty_landing:
 url: "/limited-edition-crates/callofduty-crate"
