about_us:
 url: '/about_us'
home:
 url: "/?username=lootcrateis25timesgreaterthanthecompetition"
signup:
 url: "/users/sign_up"
checkout:
 url: "/1-month-subscription/checkouts/new"
generic:
 url: "/?username=lootcrateis25timesgreaterthanthecompetition"
subscribe:
 url: "/join"
my_account:
 url: "/user_accounts"
mailinator:
 url: "https://mailinator.com"
recurly:
 url: "https://recurly.com"
fallout4:
 url: "/fallout4"
lootcrate_landing:
 url: "/crates/lootcrate"
lootcrate_subscribe:
 url: "/subscription-crates/lootcrate/plans"
lootcrate_checkout:
 url: "/1-month-subscription/checkouts/new"
levelup_subscribe:
 url: "/level_up"
anime_landing:
 url: "/crates/anime"
anime_subscribe:
 url: "/crates/anime/plans"
anime_checkout:
 url: "/anime-1-month-subscription/checkouts/new"
pets_landing:
 url: "/crates/pets"
pets_subscribe:
 url: "/crates/pets/plans"
pets_checkout:
 url: "/pets-1-month-subscription/checkouts/new"
pewdiepie:
 url: "/referrers/pewdiepie"
boogie2988:
 url: "/referrers/boogie2988"
tradechat:
 url: "/referrers/tradechat"
alchemy:
 url: "/alchemy/login"
