home:
 url: "/?username=lootcrateis25timesgreaterthanthecompetition"
signup:
 url: "/users/sign_up"
checkout:
 url: "/1-month-subscription/checkouts/new"
generic:
 url: "/?username=lootcrateis25timesgreaterthanthecompetition"
subscribe:
 url: "/join"
my_account:
 url: "/user_accounts"
mailinator:
 url: "https://mailinator.com"
recurly:
 url: "https://recurly.com"
fallout4:
 url: "/fallout4"
lootcrate_subscribe:
 url: "/crates/lootcrate/plans"
lootcrate_checkout:
 url: "/1-month-subscription/checkouts/new"
levelup_subscribe:
 url: "/level_up"
