qa:
    host: 'ec2-107-22-166-14.compute-1.amazonaws.com'
    port: '5702'
    user: 'u552tt5ivnp53u'
    password: 'p6osgimrt812s413vc4081r82j1'
    dbname: 'd1nl1de06d790v'
    redis_url: "redis://redistogo:17af1e3d5398fca6beeb4f7ade155eaa@mummichog.redistogo.com:9636/"
    prefix: "https://qa.lootcrate.com"
    admin: "https://loot-admin-qa.herokuapp.com/admin/login"
    app: "lootcrate-qa"
    base_url: "https://qa.lootcrate.com/?username=lootcrateis25timesgreaterthanthecompetition"
staging:
    host: 'ec2-54-204-24-120.compute-1.amazonaws.com'
    port: '6012'
    user: 'uc11lj39hsrm7r'
    password: 'p63dgsh1utnvdg2510sr2pk70s1'
    dbname: 'dcnfr6gdf08al'
    redis_url: "redis://redistogo:68f3acae465908685651c557e65678c4@mummichog.redistogo.com:9637/"
    prefix: "https://staging.lootcrate.com"
    admin: "https://lootcrate-staging-admin.herokuapp.com/admin/login"
    app: "lootcrate-staging"
    base_url: "https://staging.lootcrate.com/?username=lootcrateis25timesgreaterthanthecompetition"
goliath:
    host: 'ec2-107-20-133-235.compute-1.amazonaws.com'
    port: '5972'
    user: 'u38l05k018os0q'
    password: 'p8rbd0fidl2ktpb1anekidpmk32'
    dbname: 'd4drlckhi043hu'
    redis_url: "redis://redistogo:0886abb02a7f885a29fe4aa8ec642b16@mummichog.redistogo.com:10742/"
    prefix: "https://goliath.lootcrate.com"
    admin: "https://lootcrate-goliath-admin.herokuapp.com/admin/login"
    app: "lootcrate-goliath"
    base_url: "https://goliath.lootcrate.com/?username=lootcrateis25timesgreaterthanthecompetition"
qa2:
    host: 'ec2-75-101-162-128.compute-1.amazonaws.com'
    port: '5632'
    user: 'ucneac6qdaqfv4'
    password: 'p2vbo2stjftutt2khm49gp1qo1m'
    dbname: 'dcmdjpnoh3p1nq'
    redis_url: "redis://redistogo:58cd69a7595d7b49495518e54075ef41@hammerjaw.redistogo.com:10397/"
    prefix: "https://qa2.lootcrate.com"
    admin: "https://lootcrate-qa2-admin.herokuapp.com/admin/login"
    app: "lootcrate-qa2"
    base_url: "https://qa2.lootcrate.com/?username=lootcrateis25timesgreaterthanthecompetition"
qa3:
   host: 'ec2-54-225-239-220.compute-1.amazonaws.com'
   port: '5842'
   user: 'ueqgb5m2r5un3e'
   password: 'pfpb40qjfhtfv76j530etvgrce9'
   dbname: 'd55r6dllc0lr64'
   redis_url: "redis://redistogo:c9a9c62935f7b4d07945de0f0efb2806@ray.redistogo.com:9718/"
   prefix: "https://qa3.lootcrate.com"
   admin: "https://loot-admin-qa3.herokuapp.com/admin/login"
   app: "lootcrate-qa3"
   base_url: "https://qa3.lootcrate.com/?username=lootcrateis25timesgreaterthanthecompetition"
qa4:
   host: 'ec2-54-83-46-181.compute-1.amazonaws.com'
   port: '5882'
   user: 'u2l1gc325tvr8g'
   password: 'pegb4ja665bsf01v2qss99sh36m'
   dbname: 'd1jmdrjmc8ub91'
   redis_url: "redis://redistogo:c9a9c62935f7b4d07945de0f0efb2806@ray.redistogo.com:9718/"
   prefix: "https://qa4.lootcrate.com"
   admin: "https://lootcrate-qa4-admin.herokuapp.com/admin/login"
   app: "lootcrate-qa4"
   base_url: "https://qa4.lootcrate.com/?username=lootcrateis25timesgreaterthanthecompetition"
qa5:
   host: 'ec2-54-83-202-245.compute-1.amazonaws.com'
   port: '5652'
   user: 'uab4h1i6joaljg'
   password: 'p2e4rjq23j32c15octp0ofqc8fr'
   dbname: 'd1urmcba16v0pq'
   redis_url: "redis://redistogo:c9a9c62935f7b4d07945de0f0efb2806@ray.redistogo.com:9718/"
   prefix: "https://qa5.lootcrate.com"
   admin: "https://lootcrate-qa5-admin.herokuapp.com/admin/login"
   app: "lootcrate-qa5"
   base_url: "https://qa5.lootcrate.com/?username=lootcrateis25timesgreaterthanthecompetition"
load-test:
    host: 'ec2-50-17-192-85.compute-1.amazonaws.com'
    port: '5502'
    user: 'u9ce2j9e6qv4ao'
    password: 'pdp91gi35avm58acof1ps4i7stg'
    dbname: 'd43r30joboc8tg'
    redis_url: 'redis://redistogo:7ff7e7713f602b138930f5109863ed63@tetra.redistogo.com:9851/'
    prefix: "https://lootcrate-load-test.herokuapp.com"
    admin: "https://loot-admin-loadtest.herokuapp.com/admin/login"
    app: "lootcrate-load-test"
    base_url: "https://lootcrate-load-test.herokuapp.com/?username=lootcrateis25timesgreaterthanthecompetition"
local:
    host: 'localhost'
    port: '5432'
    dbname: 'lootcrate_development'
    prefix: 'localhost:3000'
